### ISSUE TITLE
Remove stack.yaml files from language dirs

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/haskell-tree-sitter#109]
#### `stack ghci` didn't work, nor did `stack build :python`
On the [`generic-building`](https://github.com/tree-sitter/haskell-tree-sitter/pull/90) branch, `stack ghci` was working from the root directory but not from `/languages/python`, which is where we do our splicing. 

@patrickt pointed out that if you’re in a directory, `stack` uses the version of ghc specified by the `resolver` in `./stack.yaml`. The parent project, `tree-sitter-haskell`, was using a modern ghc and linking all the libs correctly. However, inside the tree-sitter-python project, stack was trying to use ghc 8.2 and load in stuff compiled by 8.6, causing those errors.

#### Solution for now, and possibly forever...
Removing `stack.yaml` files from the language directories, culling the `extra-deps` in the root `stack.yaml` file made things work. 

In a separate PR, I might take all of them out (with the caveat that this makes everything very slow). 🐢

**Comment by patrickt** [comment]
I hate the slowness, but it's probably the Right Thing. We can add some flag somewhere that only builds `tree-sitter-ruby` (which is the real culprit) on CI builds.

**Comment by gasi** [comment]
Does that mean dropping support for `stack` altogether or just for these subprojects? I like the simplicity of using `stack` and `ghcid --command="stack ghci"` 😄

**Comment by patrickt** [comment]
@gasi As with our policy on `semantic`, we’ll try to enable those who choose to use `stack`, but because we don’t have the cycles to fully maintain both build systems, we won’t provide `stack.yaml` files within the repo itself. (FWIW, I recently switched from `stack` to `cabal new-build`, and I’ve been using `ghcid --command=“cabal new-repl”` to great effect—with `ghcup`, it was a pretty seamless transfer.)
