### ISSUE TITLE
Call mkSymbolDatatype in the language-specific modules?

### ISSUE THREAD

**Issue by roberth** [tree-sitter/haskell-tree-sitter#111]
This is quite a useful datatype and I missed it when hacking on a formatter for Nix recently. Do you have a specific reason not to call it in the language-specific modules? It seems like a good place for discoverability and so that it can be used across packages without unnecessary conversions.

**Comment by patrickt** [comment]
Due to historical reasons, we call it in the [semantic](https://github.com/github/semantic) project, in files like (this)[https://github.com/github/semantic/blob/master/src/Language/JSON/Grammar.hs]. I think we should move it into the language-specific modules now that `semantic` is OSS.

**Comment by robrix** [comment]
IIRC last time we tried something like this we ran into some frustrating dependency issues due to building the C code as part of the lang-specific packages. @tclem, I think it was you who worked on this; do you recall the nature of the difficulty?

If I _am_ remembering correctly, then maybe we could use the cabal 2+ support for internal libraries to work around this.

**Comment by robrix** [comment]
Going to take a look at this today since it would make some stuff I want to do in [semantic](https://github.com/github/semantic) easier.

**Comment by robrix** [comment]
@roberth: This is in place as of #112. Should be pretty easy to extend #108 to match.
