### ISSUE TITLE
Use of nested Eithers precludes using syntax nodes with * -> * interface

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#197]
While experimenting with porting `semantic-python` to use `tree-sitter-python-0.3`, I ran into a problem where I wanted to change the existing `Compile` interface, which uses `*`:

```
class Compile py where
  compile :: (Member Core sig, Carrier sig t, Foldable t, MonadFail m) => py -> m (t Name)

  default compile :: (MonadFail m, Show py) => py -> m (t Name)
  compile = defaultCompile
```

to

```
class Compile (py :: * -> *) where
  compile :: (Member Core sig, Carrier sig t, Foldable t, MonadFail m) => py Span -> m (t Name)

  default compile :: (MonadFail m, Show py) => py Span -> m (t Name)
  compile = defaultCompile
```

This would enable a greater level of concision on my part, but according to @robrix the use of nested `Either` values rather than `:.:` means that this becomes unwieldy.

See also #182.

**Comment by robrix** [comment]
More precisely, I think it’s _impossible_ using `Either`: given types `A` and `B`, a choice between them of:

```haskell
Either (A a) (B a)
```

can’t be eta-reduced to something of kind `* -> *` consistently because it applies `a` on both sides; i.e. it’s the wrong kind to develop such an instance. (That’s actually the same reason that we can’t just derive `Foldable`, `Functor`, & `Traversable` instances for syntax currently, as described in #182—the uses of `Either`s make these ill-kinded.)
