### ISSUE TITLE
symbolMatchingInstanceForSums should be kind `* -> *`

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/haskell-tree-sitter#219]
Noting this so I don't forget. As @robrix pointed out, `symbolMatchingInstanceForSums` currently generates kind `*` but we (potentially?) want `* -> *`,  just like we did for anonymous sums.

**Comment by robrix** [comment]
More precisely, I think we have the opportunity to make `Unmarshal` operate at * -> *, and thus separate out the different ways in which we unmarshal types according to what roles those types have:

- Annotations like `Range`, `Span`, and (because it operates in essentially the same manner, i.e. by looking solely at the current node) `Text`.
- TH-generated datatypes representing rules in the grammar, which we unmarshal generically.
- Field datatypes like `Maybe`, `[]`, and `NonEmpty`, which wrap some TH-generated datatype.

Making `Unmarshal` operate on type constructors of kind * -> * instead of types of kind * means that the generic machinery uses `Generic1`/`Rep1` structures, which make it _much_ easier to write instances to distinguish between the above roles:

- `Par1` is used to represent values of the type parameter; so we want to unmarshal it as an annotation.
- `K1` is used to represent values of constant type (i.e. a type not involving the type parameter); in our case, that means `Text`, so we want to unmarshal it as tho it were an annotation.
- `Rec1` is used to represent applications of a type constructor to the parameter, which in our case means AST types being applied to the type parameter (e.g. `CompoundStatement a`), so we want to unmarshal it as an AST node.
- `:.:` is a composition of types, which in our case means the application of a field-wrapping type (`Maybe`, `[]`, or `NonEmpty`) to an AST type, so we want to unmarshal it as a field. Incidentally, this is the only case where we have to handle multiple nodes!

(Anonymous sums in field types are for all intents and purposes just another kind of AST type, so they get represented within `Rec1` and thus handled by that case.)

In order to make the above work, we also need the `SymbolMatching` instances for the AST types to be defined at kind * -> *, which is a pretty straightforward matter of dropping the type parameter in the TH-generated instances.
