### ISSUE TITLE
Are you accepting pull requests?

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/haskell-tree-sitter#296]
Seeing the not merged pull requests, I'm a bit concerned.

I'm planning on maybe having a student work on this as part of gsoc, but it would be very bad to have him work on something, that has no chance of over coming to fruition.

**Comment by XVilka** [comment]
cc @patrickt @robrix @maxbrunsfeld

**Comment by siraben** [comment]
I would like to see more languages added as well, is the project still maintained?

**Comment by XVilka** [comment]
@siraben last commit was two years ago. At this point, it's obvious this project is dead. Issues and PRs are stalling without any response. Maybe a fork would be an option.

**Comment by patrickt** [comment]
@XVilka @siraben @razzeee My apologies for the radio silence on this issue and this repository. `haskell-tree-sitter` is no longer a part of our (the GitHub Semantic Code team) production code pathways, and we are but a team of seven, so we don’t have much time to maintain this library (it’s time-consuming to maintain, as there are a lot of submodules and subprojects). I’m going to take a look at #295 and #293. #294 appears to have problems with the C parser itself crashing, which I’d like to resolve first.

At this point, I think the best thing rather than a fork is to start handing out commit bits to people interested in helping maintain the library, assuming @maxbrunsfeld approves. Would anyone in this thread be interested in volunteering?

**Comment by patrickt** [comment]
It’s also worth questioning our approach. Is it too cumbersome to have _all_ these projects in one big monorepo? Or should we double down and have one gigantic project with every parser in it? That would be kind of wild, but maybe workable?

**Comment by maxbrunsfeld** [comment]
I haven’t been too involved with this Haskell binding. I’m fine with anybody taking it over; not sure if any other folks at GitHub have any plans for it.

**Comment by razzeee** [comment]
But will adding a language here, enable code navigation (etc) on github or has that moved to another integration point? If it's the later, I'm not interested in this anymore.

**Comment by patrickt** [comment]
@razzeee No, the instructions on how to add code navigation support for a language are [here](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-8-code-navigation-systems.md). We switched to a DSL for generating that information so as to prevent people from having to set up a full Haskell environment.

**Comment by dcreager** [comment]
> just adding that to my tree-sitter implementation will not add it automatically to github.com

That's correct.  We have a fixed list of language grammars (and specific pinned SHAs of those grammars) that we run in our production system.  We have an internal process for vetting any additions or changes to that list so that we can carefully measure the impact on CPU, storage, and cost.  If you have tree-sitter tagging rules for a language that you want to have included on GitHub, you can reach out to @patrickt or myself to kick off that vetting process.

**Comment by razzeee** [comment]
Thank you, will try to find time for that somewhen :)
