### ISSUE TITLE
tree-sitter/src/parser.dyn_o: multiple definition of 'tree_sitter_boreal'

### ISSUE THREAD

**Issue by Kleidukos** [tree-sitter/haskell-tree-sitter#307]
I am trying to use tree-sitter for a language that I am developing.

I am using this FFI declaration (GHC 9.6):

```haskell
import Foreign.C.ConstPtr

foreign import capi unsafe "parser.c tree_sitter_boreal"
  tree_sitter_boreal :: ConstPtr Language
```

However this gives me the following error:

```
/usr/bin/ld.gold: error: dist-newstyle/build/x86_64-linux/ghc-9.6.3/boreal-0.1.0.0/build/tree-sitter/src/parser.dyn_o: multiple definition of 'tree_sitter_boreal'

/usr/bin/ld.gold: dist-newstyle/build/x86_64-linux/ghc-9.6.3/boreal-0.1.0.0/build/Boreal/Frontend/TreeSitter.dyn_o: previous definition here

collect2: error: ld returned 1 exit status
```

What it is saying is that there are conflicting definitions of `tree_sitter_boreal`, one in the C code, and one in my Haskell code.

What's the solution here?

**Comment by brcha** [comment]
Change c-sources to cpp-sources in your cabal file, and it should work.

**Comment by Kleidukos** [comment]
@brcha hi! I believe you meant `cxx-sources`? Unfortunately I am getting the same error. Here is the branch if you wish to reproduce locally: https://github.com/Kleidukos/boreal/tree/use-tree-sitter (with the cabal file at https://github.com/Kleidukos/boreal/blob/use-tree-sitter/boreal.cabal#L48-L50)

**Comment by brcha** [comment]
@Kleidukos Yes, typo :) I thought the error was due to c linking, but it obviously is not. And it is not related to the tree-sitter lib, either.

Here's a trivial repo that reproduces the same error:

https://github.com/brcha/capi-linker-error

I made a dummy function and FFI-ed it into the Hello world program from "cabal init" and, lo and behold, multiple definitions again. So, this should be an upstream problem for the upstream, I guess.

**Comment by Kleidukos** [comment]
Damnit, thank you very much! :D I'll report to GHC, thank you <3

**Comment by brcha** [comment]
You are welcome :)

**Comment by Kleidukos** [comment]
Reported in https://gitlab.haskell.org/ghc/ghc/-/issues/24290
