### ISSUE TITLE
ts_node_copy_child_nodes is extremely slow on large ASTs

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/haskell-tree-sitter#66]
We’ve been benchmarking parsing/analysis with a large corpus of Ruby files, and encountered a severe slowdown when copying AST nodes with a great many children (the archetypal case here is Ruby code generated from an external lexer, which can generate an array literal of ~175,000 integers) into a Haskell data structure. Such bottlenecks can cause hangs on the order of tens of minutes. The suspect code is here:

```c
  uint32_t maxCount = ts_node_child_count(*parentNode);
  uint32_t max = maxCount <= count ? maxCount : count;
  for (uint32_t i = 0; i < max; i++) {
    if(i % 500 == 0) printf("iteration %lu\n", i);
    outChildNodes[i] = ts_node_elaborate(ts_node_child(*parentNode, i));
  }
```

When `max` is anything larger than ~5000 elements, this loop is pathological, and appears to slow down as iterations increase.

This for-loop is, however, embarrassingly parallelizable. We could solve this by spawning some pthreads on the C side, but that is fiddly. A better solution would be to parallelize it from the Haskell side, with a function that takes a slice of children to copy, with a signature something like this:

```c
void ts_node_copy_child_nodes_slice(const TSNode *parentNode, Node *outChildNodes, size_t count, size_t offset);
```

With a for-loop looking like `for (uint32_t i = offset; i < count; i++)`. We can then parallelize this from Haskell with some `async` or `forkIO` computations. 

We should also look into the best way to call this function from Haskell. We currently allocate the space for children with `allocaArray`, which may not be the best choice for such a large array.

**Comment by patrickt** [comment]
cc @maxbrunsfeld on this, who may have some insights on how to speed up this copying process

**Comment by patrickt** [comment]
A good example of a file that chokes here is [this encoding table](https://github.com/ruby/ruby/blob/trunk/enc/trans/big5-uao-tbl.rb) from the Ruby implementation—one 19,000-item array.

**Comment by patrickt** [comment]
We may also want to look into using `Data.Vector` for this, given how large the array can be, and that we know its size.

**Comment by maxbrunsfeld** [comment]
One thing that jumped out at me is that the `ts_node_child()` function isn't well suited for calling in a loop that walks the tree like this. You might expect it to be a constant time operation, but it's actually logarithmic with respect to the node's child count, because node lists are stored as balanced binary trees.

For purposes like this, there's a different API that you should use - the [`TSTreeCursor`](https://github.com/tree-sitter/tree-sitter/blob/master/include/tree_sitter/runtime.h#L136). You can walk the whole tree much more efficiently using the `ts_tree_cursor_goto_first_child`, `ts_tree_cursor_goto_next_sibling`, and `ts_tree_cursor_goto_parent` methods, which imperatively move the cursor around the tree.

**Comment by patrickt** [comment]
@maxbrunsfeld Aha! This is exactly what I want, and explains why the loop was getting so much slower on each iteration. Thank you so much!

**Comment by maxbrunsfeld** [comment]
Also, [just now I added](https://github.com/tree-sitter/tree-sitter/commit/af01846fd7a665ffbcfe96d7700e276e02133d6c) one missing function that I've been meaning to add for a while, `ts_tree_cursor_reset(cursor, node)`, so you can keep using a given cursor, but reset it to a different starting node. Depending on your procedure for walking in the tree, this might be helpful, since creating a cursor entails one heap allocation, so it's nice to avoid creating and destroying them repeatedly.

**Comment by maxbrunsfeld** [comment]
Oh wow, I just found a *second* reason that this is slow, specific to [the way arrays are parsed](https://github.com/tree-sitter/tree-sitter-ruby/blob/master/grammar.js#L396-L400) in `tree-sitter-ruby`.

We actually were *not* using the normal `repeat` rule for parsing the elements of the array, so we weren't taking advantage of Tree-sitter's tree-balancing. The explicit recursive structure we were specifying meant that the nodes were basically stored in a right-leaning linked list 😱 .

That's fixed now.

**Comment by maxbrunsfeld** [comment]
Before:

![screen shot 2018-10-21 at 10 57 14 am](https://user-images.githubusercontent.com/326587/47270403-228aed80-d520-11e8-8fa4-c22ab34b0203.png)

After:

![screen shot 2018-10-21 at 10 56 07 am](https://user-images.githubusercontent.com/326587/47270400-1dc63980-d520-11e8-9525-0deaee58fa68.png)

**Comment by patrickt** [comment]
@maxbrunsfeld Wow! That’s incredible. Using `TSCursor` (and avoiding unnecessary stack allocations) sped this loop up by a factor of 240 (!), so we both crushed this!

**Comment by maxbrunsfeld** [comment]
Nice!! 🤜🤛

**Comment by patrickt** [comment]
@maxbrunsfeld Pulling in the new tree-sitter-ruby shaved another good bit off the time, so high fives to you!

**Comment by domenkozar** [comment]
@maxbrunsfeld we're trying to investigate https://github.com/hercules-ci/canonix/issues/9 and I'm wondering how did you manage to produce that graph?

**Comment by domenkozar** [comment]
@patrickt I haven't digged into the details, but how come we can't use http://tree-sitter.github.io/tree-sitter/using-parsers#concurrency instead of copying?

**Comment by maxbrunsfeld** [comment]
> how come we can't use http://tree-sitter.github.io/tree-sitter/using-parsers#concurrency instead of copying?

I think `ts_node_copy_child_nodes` is used for importing the nodes into a haskell data structure; it's not copying them in order to use them on a different thread.

> how did you manage to produce that graph?

If you run `tree-sitter parse a-file -D`, it will generate a series of graph to help you debug the parse. You need to have graphviz (specifically, the `dot` command) installed in order to render the graphs.

**Comment by patrickt** [comment]
> I think ts_node_copy_child_nodes is used for importing the nodes into a haskell data structure; it's not copying them in order to use them on a different thread.

Yup, that’s the issue. It is [here](https://github.com/github/semantic/blob/master/src/Parsing/TreeSitter.hs#L85) that we need to copy the data across the FFI boundary and then marshal it into a Haskell list with `peekArray`.
