### ISSUE TITLE
Building AST values ignores symbols

### ISSUE THREAD

**Issue by robrix** [tree-sitter/haskell-tree-sitter#95]
We select the first child of sums which successfully builds (based on its child fields), rather than selecting one based on the symbol. This is incorrect and inefficient.

cf #144.

**Comment by aymannadeem** [comment]
**Context:** when we construct tree-sitter grammars, we name rules with strings like `if_statement`. `tree-sitter` maps each to a short int. Each such int is unique for the grammar rule name, and so we call them symbols. We currently use _field names_, not symbols. However, we need to use the symbol for the current node to pick which constructor of a sum we should attempt to match with, rather than using `Alternative` to try both and backtrack.

**Comment by aymannadeem** [comment]
Fixed
